@startuml DiagramaClasses

Class Edital {
    +Integer id
    +String titulo
    +String objeto
    +Date publicacao
    +String arquivo
    +Salvar()
    +Ler()
    +Editar()
    +Deletar()
}

Class Edital_Vagas {
    +Integer id
    +Integer editalId
    +String modalidade
    +Integer qtVagas
    +Float valor
    +Integer vigencia
    +Salvar()
    +Ler()
    +Editar()
    +Deletar()
}

Class Instituicao {
    +Integer id
    +String nome
    +String logradouro
    +String bairro
    +String municipio
    +String cidade
    +String estado
    +String cep
    +Integer administradorId
    +Salvar()
    +Ler()
    +Editar()
    +Deletar()
}

Class Usuario {
    +String cpf
    +String nome
    +String email
    +String Celular
    +Date datanasc
}

Class Administrador {
    +cadastrar_instituicao()
    +validar_cadastro_usuario()
    +atribuir_perfil()
}

Class Coordenador {
    +cadastrar_projeto()
    +cadastrar_bolsista()
    +substituir_bolsista()
}

Class Projeto {
    +Integer id
    +String ProjetoNum
    +String titulo
    +Integer IntituicaoId
    +Integer CoordenadorId
}

Class BolsistaProjeto {
    +Integer id
    +Integer projetoId
    +String cpfBolsista
}

Class Bolsista {
    +date dt_matricula
    +Integer cursoId

    +inserir_comprovante()

}

Class Curso {
    +Integer id
    +String nome
    +String categoria

}

Usuario <|-- Administrador
Usuario <|-- Coordenador
Usuario <|-- Bolsista

Edital "1" *-- "1..*" Edital_Vagas
Edital "1" *-- "0..*" Projeto
Projeto "1" *-- "1" Coordenador
Projeto "1" *-- "1..*" Bolsista
Administrador "1" *-- "0..*" Instituicao
Instituicao "*" -- "*" Curso
Bolsista "1" *-- "1" Curso

@enduml





